#!/bin/sh

# Fail if any command fails
set -e

echo "📦 iOS CI Post-Clone Script"

# Determine project root - handle both direct and nested structures
if [ -d "${CI_WORKSPACE}/myagenda_app/myagenda_app" ]; then
  # Nested structure detected
  PROJECT_ROOT="${CI_WORKSPACE}/myagenda_app/myagenda_app"
else
  # Direct structure
  PROJECT_ROOT="${CI_WORKSPACE}/myagenda_app"
fi

echo "🔍 Project root detected at: ${PROJECT_ROOT}"

# Navigate to project root
cd "${PROJECT_ROOT}"

# Install Flutter dependencies
echo "🔄 Running flutter pub get"
flutter pub get

# Pre-cache Flutter binaries and artifacts
echo "📦 Pre-caching Flutter"
flutter precache

# Ensure iOS build artifacts are generated
echo "⚙️ Building iOS (no codesign) to generate configs"
flutter build ios --no-codesign

# Navigate to iOS folder
cd ios

# Check for and install CocoaPods if needed
if ! command -v pod &> /dev/null; then
  echo "🔧 Installing CocoaPods"
  sudo gem install cocoapods
fi

# Clean up old Pods (optional, but helps avoid .xcfilelist issues)
echo "🧹 Cleaning Pods"
pod deintegrate || true
rm -rf Pods
rm -f Podfile.lock

# Install Pods
echo "📦 Installing CocoaPods dependencies"
pod install

# Confirm that Generated.xcconfig exists
if [ ! -f "Flutter/Generated.xcconfig" ]; then
  echo "⚠️ Generated.xcconfig not found after build. Attempting fallback pub get + build"
  cd "${PROJECT_ROOT}"
  flutter pub get
  flutter build ios --no-codesign
  cd ios
fi

# Final check and fallback if file still not found
if [ ! -f "Flutter/Generated.xcconfig" ]; then
  echo "❗ Still missing Generated.xcconfig — creating minimal fallback"
  mkdir -p Flutter
  echo "// Fallback Generated.xcconfig generated by ci_post_clone.sh" > Flutter/Generated.xcconfig
  echo "FLUTTER_ROOT=${FLUTTER_ROOT}" >> Flutter/Generated.xcconfig
  echo "FLUTTER_APPLICATION_PATH=${PROJECT_ROOT}" >> Flutter/Generated.xcconfig
  echo "FLUTTER_TARGET=${PROJECT_ROOT}/lib/main.dart" >> Flutter/Generated.xcconfig
  echo "FLUTTER_BUILD_DIR=build" >> Flutter/Generated.xcconfig
fi

echo "✅ iOS CI Post-Clone Script completed successfully"